
- name: app setup 
  include_role:
    name: common
    tasks_from: appsetup


- name: set up nodejs
  include_role: 
    name: common
    tasks_from: nodejs

- name: set up systemd
  include_role: 
    name: common
    tasks_from: systemd.yaml