- name: disable current  nodejs  module
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable  nodejs:20  module
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Install  node.js package.
  community.general.npm:
    name: nodejs
    path: /app
