- name: Setup SystemD {{ component }} Service copy the file to SystemD
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"
    # change to copy means [copy as it from there]
    # but now it will go template folder then go to {{ component }}.service change to{{ component }}.service.j2
    # from there it  

- name: Load the service.systemctl deamon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable service {{ component }}
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted # even app is not ruuning restart 
    enabled: yes 
